version: '3'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"         # HTTP
      - "81:81"         # Panel de control
      - "443:443"       # HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
