version: '3.1'

services:
  web:
    image: php:8.3-apache
    container_name: apache-php
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/webserver:/var/www/html/
    network_mode: host